menu:
  Home: /
  Archives: /archives/
  About: /about/
  Subscribe: /atom.xml

widgets:
- menu
- category
- tagcloud

excerpt_link: Read More

fancybox: true

# 友言评论
UYUserId:

# cnzz统计
cnzzId:

# JiaThis分享
jiathisUUID:

weibo:
	name:
	uid:
	link:

github:
  name: scalaview
  link: https://github.com/scalaview

rss: http://xxx.xx/atom.xml